apiVersion: v1
kind: Service
metadata:
  name: firefox-service
  labels:
    app: firefox
spec:
  type: LoadBalancer
  selector:
    app: firefox
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080   # Access via <NodeIP>:30080
    - name: websocket
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30081   # Access via <NodeIP>:30081
