apiVersion: v1
kind: Pod
metadata:
  name: firefox-pod
  labels:
    app: firefox
spec:
  containers:
    - name: firefox
      image: lscr.io/linuxserver/firefox:latest
      ports:
        - containerPort: 3000
        - containerPort: 3001
      env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Kolkata"
      volumeMounts:
        - name: firefox-config
          mountPath: /config
  volumes:
    - name: firefox-config
      emptyDir: {}
