apiVersion: v1
kind: Service
metadata:
  name: healthcheck-service
spec:
  selector:
    app: healthcheck
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80          # External port
    targetPort: 80    # Pod's containerPort
