apiVersion: v1
kind: Pod
metadata:
  name: healthcheck-pod
  labels:
    app: healthcheck
spec:
  containers:
  - name: healthcheck-pro
    image: ajayacr92.azurecr.io/healthcheck-pro:v1
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
